{
 "title": "Deus Monitor",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(cosmos_validators_rank, chain_id)"
    }
   },
   {
    "name": "moniker",
    "label": "Moniker",
    "query": {
     "query": "label_values(cosmos_validators_status{chain_id=\"$chain_id\"}, moniker)"
    }
   },
   {
    "name": "denom",
    "query": {
     "query": "label_values(cosmos_wallet_balance{chain_id=\"$chain_id\"}, denom)"
    }
   },
   {
    "name": "chain_name",
    "query": {
     "query": "label_values(tendermint_p2p_peers{chain_id=\"$chain_id\"}, group)"
    }
   },
   {
    "name": "validator_addr",
    "query": {
     "query": "label_values(cosmos_validators_status{chain_id=\"$chain_id\", moniker=\"$moniker\"}, address)"
    }
   },
   {
    "name": "price_url",
    "query": {
     "query": "CollectionLookup(juno,https://api-osmosis.imperator.co/tokens/v1/JUNO,stars,https://deuslabs.fi,$denom)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 0 },
   "options": {
    "content": "<h3 style=\"text-align: center;margin: 5px 0px\"><span style=\"color: #F0827D;\"><span style=\"color: RGBA(240, 130, 125,0.5);\">from&nbsp</span> <a href=\"https://deuslabs.fi\" style=\"color:RGB(255, 220, 200);\">deus labs<img width=\"40px\" src=\"https://avatars.githubusercontent.com/u/89633644?s=400&u=95bfd2cbd13207ef992683493742df97e34a7acc&v=4\" style=\"margin: 0px 5px\"/></a></span></h3>"
   }
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 2, "w": 11, "x": 11, "y": 0 } },
  { "type": "yesoreyeram-boomtheme-panel", "gridPos": { "h": 1, "w": 1, "x": 23, "y": 0 } },
  { "title": "Validator Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 1, "x": 0, "y": 3 },
   "options": {
    "content": "<img width=\"60px\" src=\"https://raw.githubusercontent.com/cosmostation/cosmostation_token_resource/master/moniker/$chain_name/$validator_addr.png\" alt=\"$moniker\" style=\"margin: 30px 0px\"/>"
   }
  },
  {
   "title": "rank",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 1, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(cosmos_validators_rank{chain_id=\"$chain_id\", moniker=\"$moniker\"})",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "total delegations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_delegator_shares{chain_id=\"$chain_id\", moniker=\"$moniker\"}",
     "legendFormat": "{{denom}}"
    }
   ]
  },
  {
   "title": "voting power percentage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_tokens{chain_id=\"$chain_id\", moniker=\"$moniker\"} OR on() vector(0)",
     "legendFormat": "validator power"
    },
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\", instance=\"sentry1\"}",
     "legendFormat": "total power"
    }
   ]
  },
  {
   "title": "commission rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_commission{chain_id=\"$chain_id\", moniker=\"$moniker\"}"
    }
   ]
  },
  {
   "title": "missed blocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validators_missed_blocks{chain_id=\"$chain_id\", moniker=\"$moniker\"}",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  { "title": "Network Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 1, "x": 0, "y": 10 },
   "options": {
    "content": "<img width=\"60px\" src=\"https://raw.githubusercontent.com/cosmostation/cosmostation_token_resource/master/chains/logo/$chain_name.png\"  style=\"margin: 30px 0px\"/>"
   }
  },
  {
   "title": "price",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 1, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "price", "text": " ", "type": "number" }
     ],
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "source": "url",
     "type": "json",
     "url": "$price_url",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "token stats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      {
       "selector": "staking_pool.pool.bonded_tokens",
       "text": "bonded",
       "type": "string"
      },
      { "selector": "minting_inflation.inflation", "text": "inflation", "type": "number" }
     ],
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "json_options": {
      "root_is_not_array": false
     },
     "root_selector": "Params",
     "source": "url",
     "type": "json",
     "url": "https://api-utility.cosmostation.io/v1/params/$chain_id",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "amount", "text": "supply", "type": "string" }
     ],
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "json_options": {
      "root_is_not_array": false
     },
     "root_selector": "$.Params.supply.supply[?(@.denom=='u$denom')]",
     "source": "url",
     "type": "json",
     "url": "https://api-utility.cosmostation.io/v1/params/$chain_id",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "bonded tokens",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\",instance=\"sentry1\"}",
     "legendFormat": "{{ denom }}"
    }
   ]
  },
  {
   "title": "block height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 1, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_height{chain_id=\"$chain_id\", instance=\"sentry1\"}"
    }
   ]
  },
  {
   "title": "validators",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 7, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validators_active{chain_id=\"$chain_id\"})",
     "legendFormat": "total validators"
    },
    {
     "expr": "count(cosmos_validators_active{chain_id=\"$chain_id\"} > 0)",
     "legendFormat": "active validators"
    },
    {
     "expr": "count(cosmos_validators_active{chain_id=\"$chain_id\"} == 0)",
     "legendFormat": "inactive validators"
    },
    {
     "expr": "count(cosmos_validators_jailed{chain_id=\"$chain_id\"} > 0)",
     "legendFormat": "jailed validators"
    }
   ]
  },
  {
   "title": "total transactions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_total_txs{chain_id=\"$chain_id\", instance=\"sentry1\"}"
    }
   ]
  },
  { "title": "All Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "delegator shares",
   "type": "piechart",
   "gridPos": { "h": 19, "w": 13, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(cosmos_validators_delegator_shares{chain_id=\"$chain_id\"})",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "missed blocks",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 10, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(cosmos_validators_missed_blocks{chain_id=\"$chain_id\"})",
     "legendFormat": "{{ moniker }}"
    }
   ]
  }
 ]
}