{
 "title": "Home",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(cosmos_validators_rank, chain_id)"
    }
   },
   {
    "name": "moniker",
    "label": "Moniker",
    "query": {
     "query": "label_values(cosmos_validator_commission{chain_id=\"$chain_id\"}, moniker)"
    }
   },
   {
    "name": "walletaddr",
    "query": {
     "query": "label_values(cosmos_wallet_balance{chain_id=\"$chain_id\"}, address)"
    }
   },
   {
    "name": "denom",
    "query": {
     "query": "label_values(cosmos_wallet_balance{chain_id=\"$chain_id\"}, denom)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 1, "y": 0 },
   "options": {
    "content": "<img width=\"50px\" src=\"https://avatars.githubusercontent.com/u/89633644?s=400&u=95bfd2cbd13207ef992683493742df97e34a7acc&v=4\" style=\"margin: 0px 25px\"/>\n"
   }
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 2, "w": 6, "x": 9, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "options": {
    "content": "<img width=\"50px\" src=\"https://raw.githubusercontent.com/cosmostation/cosmostation_token_resource/master/chains/logo/$denom.png\" />"
   }
  },
  {
   "title": "validator rank",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(cosmos_validator_rank{chain_id=\"$chain_id\", moniker=\"$moniker\"})",
     "legendFormat": "{{ moniker }}"
    },
    {
     "expr": "count(cosmos_validators_active{chain_id=\"$chain_id\"})",
     "legendFormat": "total validators"
    }
   ]
  },
  {
   "title": "price",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "price", "text": " ", "type": "number" }
     ],
     "csv_options": {
      "columns": "",
      "comment": "",
      "delimiter": ",",
      "relax_column_count": false,
      "skip_empty_lines": false,
      "skip_lines_with_error": false
     },
     "source": "url",
     "type": "json",
     "url": "https://api-osmosis.imperator.co/tokens/v1/$denom",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "commission",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validator_commission{chain_id=\"$chain_id\", moniker=\"$moniker\"}",
     "legendFormat": "{{ denom }}"
    }
   ]
  },
  {
   "title": "total delegations",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cosmos_validator_delegations{chain_id=\"$chain_id\", moniker=\"$moniker\"}) by (denom)",
     "legendFormat": "{{denom}}"
    }
   ]
  },
  {
   "title": "projected commission (daily)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validator_commission{chain_id=\"$chain_id\", moniker=\"$moniker\"} offset 1d",
     "legendFormat": "day-current"
    },
    {
     "expr": "predict_linear(cosmos_validator_commission{chain_id=\"$chain_id\", moniker=\"$moniker\"}[1d] offset 30m, 1)",
     "legendFormat": "day-prediction"
    }
   ]
  },
  {
   "title": "projected commission (weekly)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validator_commission{chain_id=\"$chain_id\", moniker=\"$moniker\"} offset 7d",
     "legendFormat": "week-current"
    },
    {
     "expr": "predict_linear(cosmos_validator_commission{chain_id=\"$chain_id\", moniker=\"$moniker\"}[7d], 1)",
     "legendFormat": "week-prediction"
    }
   ]
  },
  {
   "title": "projected commission (monthly)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validator_commission{chain_id=\"$chain_id\", moniker=\"$moniker\"} offset 30d",
     "legendFormat": "month-current"
    },
    {
     "expr": "predict_linear(cosmos_validator_commission{chain_id=\"$chain_id\", moniker=\"$moniker\"}[30d], 1)",
     "legendFormat": "month-prediction"
    }
   ]
  },
  {
   "title": "total rewards",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validator_rewards{chain_id=\"$chain_id\", moniker=\"$moniker\"}",
     "legendFormat": "{{ denom }}"
    }
   ]
  },
  {
   "title": "operator wallet balance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_wallet_balance{chain_id=\"$chain_id\", address=\"$walletaddr\"}",
     "legendFormat": "{{ denom }}"
    }
   ]
  },
  {
   "title": "commission rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validator_commission_rate{chain_id=\"$chain_id\", moniker=\"$moniker\"}"
    }
   ]
  },
  {
   "title": "delegators",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(cosmos_validator_delegations{chain_id=\"$chain_id\", moniker=\"$moniker\"})",
     "legendFormat": "{{delegated_by}}"
    }
   ]
  },
  {
   "title": "delegation counts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validator_delegations{chain_id=\"$chain_id\", moniker=\"$moniker\"})",
     "legendFormat": "delegations"
    },
    {
     "expr": "count(cosmos_validator_redelegations{chain_id=\"$chain_id\", moniker=\"$moniker\"}) OR on() vector(0)",
     "legendFormat": "redelegations"
    },
    {
     "expr": "count(cosmos_validator_unbondings{chain_id=\"$chain_id\", moniker=\"$moniker\"}) OR on() vector(0)",
     "legendFormat": "unbondings"
    }
   ]
  },
  {
   "title": "total redelegations and unbondings",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cosmos_validator_redelegations{chain_id=\"$chain_id\", moniker=\"$moniker\"}) by (moniker, denom) OR on() vector(0)",
     "legendFormat": "redelegations {{denom}}"
    },
    {
     "expr": "sum(cosmos_validator_unbondings{chain_id=\"$chain_id\", moniker=\"$moniker\"}) by (moniker, denom)",
     "legendFormat": "unbondings, {{denom}}"
    }
   ]
  },
  {
   "title": "missed blocks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validator_missed_blocks{chain_id=\"$chain_id\", moniker=\"$moniker\"}",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node\"}[$__rate_interval])*8",
     "legendFormat": "{{instance}}-recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node\"}[$__rate_interval])*8",
     "legendFormat": "{{instance}}-trans {{device}} "
    }
   ]
  },
  {
   "title": "block height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_height{chain_id=\"$chain_id\", instance=\"sentry1\"}"
    }
   ]
  },
  {
   "title": "voting power percentage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validator_power{chain_id=\"$chain_id\"}"
    },
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\", instance=\"sentry1\"}"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{chain_id=\"$chain_id\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "tokens by validator",
   "type": "piechart",
   "gridPos": { "h": 18, "w": 15, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(cosmos_validators_tokens{chain_id=\"$chain_id\"})",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  { "title": "Detailed Dashboards", "type": "dashlist", "gridPos": { "h": 10, "w": 5, "x": 0, "y": 27 } }
 ]
}