{
 "title": "Juno Network Dashboard",
 "description": "A dashboard for Terra blockchain (https://terra.money/) node using Prometheus.\nThis dashboard shows several important metrics of default terra metrics collected by Prometheus.\nMaintained by dsrv labs (http://www.dsrvlabs.com) and please take a look at https://www.dsrvlabs.com/blog/news/monitoring_for_terra/ for more information.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "jobfilter", "label": "job" },
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Liveness",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Liveness" }
   ],
   "targets": [
    { "expr": "up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tendermint_p2p_peers", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Block Height",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tendermint_consensus_height", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Block Interval (secs)",
   "type": "graph",
   "description": "Time between this and last block (Block.Header.Time) in seconds\n#\nDoesn't seem to receive any",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tendermint_consensus_block_interval_seconds_bucket[5m])) by (le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tendermint_consensus_num_txs", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Tendermint Mempool Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tendermint_mempool_size", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Tendermint Block Size (bytes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Amount Validators",
   "type": "gauge",
   "description": "Number of validators",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Validators Missing",
   "type": "gauge",
   "description": "Number of validators who did not sign",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Byzantine Validators",
   "type": "gauge",
   "description": "Number of validators who tried to double sign",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_byzantine_validators",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Missing + Byzantine Validators",
   "type": "gauge",
   "description": "Percentage of missing + byzantine validators",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((tendermint_consensus_byzantine_validators_power + tendermint_consensus_missing_validators_power) / tendermint_consensus_validators_power) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Voting Power",
   "type": "gauge",
   "description": "Total voting power of all validators",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Voting power of the missing validators",
   "type": "gauge",
   "description": "Total voting power of the missing validators",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators_power",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Voting Power of Byzantine Validators",
   "type": "gauge",
   "description": "Total voting power of the byzantine validators",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_byzantine_validators_power",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "# of Validators",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_validators",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Voting Power",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none", "label": "STEAK" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Absent Validators",
   "type": "graph",
   "description": "Number of validators who did not sign",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "# of Missing or Byzantine Validators",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(tendermint_consensus_missing_validators + tendermint_consensus_byzantine_validators)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Process Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Process Resident Memory (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Process Virtual Memory (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Number of gorutines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Process open/max fds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "{{instance}}-open" },
    { "expr": "process_max_fds", "legendFormat": "{{hostname}}-max" }
   ]
  }
 ]
}