{
 "title": "Wallet",
 "description": "Stats of a Cosmos wallet",
 "tags": [
  "cosmos",
  "blockchain",
  "wallet"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(cosmos_wallet_balance, chain_id)"
    }
   },
   {
    "name": "address",
    "label": "Address",
    "query": {
     "query": "label_values(cosmos_wallet_balance{chain_id=\"$chain_id\"}, address)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_wallet_balance{chain_id=\"$chain_id\", address=\"$address\"}",
     "legendFormat": "{{ denom }}"
    }
   ]
  },
  {
   "title": "delegations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_wallet_delegations{chain_id=\"$chain_id\", address=\"$address\"}) or on() vector(0)",
     "legendFormat": "{{ address }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "rewards",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cosmos_wallet_rewards{chain_id=\"$chain_id\", address=\"$address\"}) by (address, denom)",
     "legendFormat": "{{address}}, {{denom}}"
    }
   ]
  },
  {
   "title": "redelegations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_wallet_redelegations{chain_id=\"$chain_id\", address=\"$address\"}) or on() vector(0)",
     "legendFormat": "{{ address }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "unbondings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_wallet_unbondings{chain_id=\"$chain_id\", address=\"$address\"}) or on() vector(0)",
     "legendFormat": "{{ address }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "delegations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cosmos_wallet_delegations{chain_id=\"$chain_id\", address=\"$address\"}) by (address, denom)",
     "legendFormat": "{{ address }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "delegations",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cosmos_wallet_delegations{chain_id=\"$chain_id\", address=\"$address\"}",
     "legendFormat": "{{ address }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "redelegations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cosmos_wallet_redelegations{chain_id=\"$chain_id\", address=\"$address\"}) or on() vector(0)",
     "legendFormat": "{{ address. }}"
    }
   ]
  },
  {
   "title": "redelegations",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "cosmos_wallet_redelegations{chain_id=\"$chain_id\", address=\"$address\"}"
    }
   ]
  },
  {
   "title": "unbondings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cosmos_wallet_unbondings{chain_id=\"$chain_id\", address=\"$address\"}) by (address, denom)",
     "legendFormat": "{{ address }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "unbondings",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "sum(cosmos_wallet_unbondings{chain_id=\"$chain_id\", address=\"$address\"}) by (unbonded_from, denom)",
     "legendFormat": "{{ unbonded_from }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "balance history",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cosmos_wallet_balance{chain_id=\"$chain_id\", address=\"$address\"}",
     "legendFormat": "{{ denom }}"
    }
   ]
  }
 ]
}